version: "3.9"
services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
  redis:
     image: redis:6.2.4
     ports:
       - '6379:6379'
     volumes:
       - redis:/var/lib/redis/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/workspaces/sva
    ports:
      - "3000:3000"
    depends_on:
      - db
  sidekiq:
    build: .
    depends_on:
      - redis
      - web
      - db
    command: bundle exec sidekiq
    volumes:
      - .:/workspaces/sva
volumes:
  postgres:
  redis:
